const GET_USER = "GET_USER";
const SET_USER = "SET_USER";
const UPDATE_USER = "UPDATE_USER";
const USER_UPLOAD = "USER_UPLOAD";

const USER_SELECTED = "USER_SELECTED";

export { USER_SELECTED, USER_UPLOAD, GET_USER, SET_USER, UPDATE_USER };
